### ISSUE TITLE
mas uninstall - incorrect components were removed

### ISSUE THREAD

**Issue by rene-oromtz** [ibm-mas/installer#1090]
CLI Version
----

IBM Maximo Application Suite Admin CLI v10.0.2

MAS CLI Input
----
```
3) Uninstall MAS Dependencies
Uninstall Certificate Manager? No
Uninstall MongoDb? Yes
Uninstall IBM Suite Licensing Service? Yes
Uninstall Grafana? NO
Uninstall IBM Catalog Source? no
Uninstall IBM Common Services? yes
Uninstall IBM User Data Services? yes

4) Review Settings
Instance ID ..................... cpst3
Uninstall Cert-Manager .......... False (redhat)
Uninstall Grafana ............... False
Uninstall IBM Operator Catalog .. False
Uninstall IBM Common Services ... True
Uninstall UDS ................... True
Uninstall MongoDb ............... False
Uninstall SLS ................... False
```

Expected Behaviour
----
MongoDB, Common-Services and UDS should have been removed along with MAS coomponents

Actual Behavior
----
Common-Services, UDS and IBM-Catalogs were removed from the cluster

Analysis
----

Two issues here:

1. For Mongo/SLS, those weren't removed because it was specified as "Yes"

From mas-uninstall, only options for specifying an affirmative answers is y or yes
`uninstallMongoDb = prompt(HTML(f'<Yellow>Uninstall MongoDb? </Yellow>'), validator=YesNoValidator()) in ["y", "yes"]`
This is why the setting were set as False:
```
Uninstall MongoDb ............... False
Uninstall SLS ................... False
```
While there is warning showing the valid answers, this is not getting enforced as it takes "Yes" as a valid response. Possible enhancement is to either "lower" the response from customer or to add "Yes", "Y" as possible answers. 

2. Even when IBM Operator Catalog was set to False, it got uninstalled from cluster, for this, I'm not entirely sure which portion of the code is the one that is sending the wrong response to the pipelines:
```
Uninstall IBM Operator Catalog .. False
```
![image](https://github.com/ibm-mas/cli/assets/157750458/074f62e8-43e6-43a5-8524-c141306b4ba5)

```
oc get catsrc -A
NAMESPACE               NAME                  DISPLAY               TYPE   PUBLISHER   AGE
openshift-marketplace   certified-operators   Certified Operators   grpc   Red Hat     21d
openshift-marketplace   community-operators   Community Operators   grpc   Red Hat     21d
openshift-marketplace   redhat-marketplace    Red Hat Marketplace   grpc   Red Hat     21d
openshift-marketplace   redhat-operators      Red Hat Operators     grpc   Red Hat     21d

```

**Comment by rene-oromtz** [comment]
I just found where the YesNoValidator is located, seems that right here it is allowing Y or Yes as a valid answer:
```
class YesNoValidator(Validator):
    def validate(self, document):
        """
        Validate that a response is understandable as a yes/no response
        """
        response = document.text
        if response.lower() not in ["y", "n", "yes", "no"]:
            raise ValidationError(message='Enter a valid response: y(es), n(o)', cursor_position=len(response))
```

However, like mentioned before, the Uninstall is only taking `yes` or `y` as valid

```
uninstallMongoDb = prompt(HTML(f'<Yellow>Uninstall MongoDb? </Yellow>'), validator=YesNoValidator()) in ["y", "yes"]
```

**Comment by durera** [comment]
Fix incoming ... 

![image](https://github.com/ibm-mas/cli/assets/4400618/9ab13e2a-a0c9-4e35-8ac7-3481196c7ca4)

**Comment by durera** [comment]
Additional enhancements:

![image](https://github.com/ibm-mas/cli/assets/4400618/acaa0fe5-2935-4a4c-bddf-fede2d219859)

![image](https://github.com/ibm-mas/cli/assets/4400618/fa85de7e-d10d-4445-afc1-e4d295aabd0e)

**Comment by durera** [comment]
In terms of the second issue raised .. I think they must have been related:

Selecting these options: 
![image](https://github.com/ibm-mas/cli/assets/4400618/6f3760cf-e284-4697-becf-139ceb0d19c9)

Resulted in this pipeline configuration

```
  params:
    - name: mas_instance_id
      value: fvtstable
    - name: grafana_action
      value: none
    - name: cert_manager_provider
      value: redhat
    - name: cert_manager_action
      value: none
    - name: common_services_action
      value: none
    - name: ibm_catalogs_action
      value: none
    - name: mongodb_action
      value: none
    - name: sls_action
      value: none
    - name: uds_action
      value: none
```
