### ISSUE TITLE
Unable to set --skip-pre-check on MAS Upgrade

### ISSUE THREAD

**Issue by rene-oromtz** [ibm-mas/installer#1107]
CLI Version
----

IBM Maximo Application Suite Admin CLI v10.0.6

MAS CLI Input
----
```
mas upgrade --skip-pre-check

IBM Maximo Application Suite Admin CLI v10.0.6
Powered by https://github.com/ibm-mas/ansible-devops/ and https://tekton.dev/


1) Set Target OpenShift Cluster
Already connected to OCP Cluster:
 https://console-openshift-console.apps.ocp-d.cpst-lab.ibm.com

Proceed with this cluster? yes

2) Instance Selection
Select a MAS instance to upgrade from the list below:
- ocpdmas v8.11.12

Enter MAS instance ID: ocpdmas

3) Review Settings
Instance ID ..................... ocpdmas
Skip Pre-Upgrade Checks ......... True

Proceed with these settings? yes

4) Launch Upgrade
✅️ OpenShift Pipelines Operator is installed and ready to use
✅️ Namespace is ready (mas-ocpdmas-pipelines)
✅️ Latest Tekton definitions are installed (v10.0.6)
✅️ PipelineRun for ocpdmas upgrade submitted
```

Expected Behaviour
----
The skip pre check should allow to bypass the check in case there is a non related Maximo error 

Actual Behavior
----
Skip Pre Check is not getting honored, the pre check is still launched:
![image](https://github.com/ibm-mas/cli/assets/157750458/84534c1c-10c2-40c8-b426-b665855d196c)

Analysis
----

On MAS upgrade, the skip-pre-check is properly being set.

I was looking at python-devops repo and I believe the problem might reside there:
From tekton.py the skip pre check is a valid argument:

```
def launchUpgradePipeline(dynClient: DynamicClient,
                          instanceId: str,
                          skipPreCheck: bool = False,
                          masChannel: str = "") -> str:
    """
    Create a PipelineRun to upgrade the chosen MAS instance
    """
...
    template = env.get_template("pipelinerun-upgrade.yml.j2")
    renderedTemplate = template.render(
        timestamp=timestamp,
        mas_instance_id=instanceId,
        skip_pre_check=skipPreCheck,
        mas_channel=masChannel
    )
```

However, on the` pipelinerun-upgrade.yml.j2` I don't see any reference to this variable:
```
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "{{ mas_instance_id }}-upgrade-{{ timestamp }}"
  labels:
    tekton.dev/pipeline: mas-upgrade
spec:
  pipelineRef:
    name: mas-upgrade

  serviceAccountName: pipeline
  timeouts:
    pipeline: "10h"

  params:
    - name: mas_instance_id
      value: "{{ mas_instance_id }}"
    - name: mas_channel
      value: "{{ mas_channel }}"
```

The install template does include a reference for skip pre check:
```
{%- if skip_pre_check is defined and skip_pre_check != "" %}

    # Pipeline config
    # -------------------------------------------------------------------------
    - name: skip_pre_check
      value: "{{ skip_pre_check }}"
```
