### ISSUE TITLE
MAS Install Pipeline fails on UDS

### ISSUE THREAD

**Issue by belfortmaycon** [ibm-mas/installer#368]
Hi Team, I'm installing MAS 8.10, and my pipeline is failing on the UDS step.

I checked the pods, and the `store-api-deployment` was failing and restarting. In the logs for this pod, I found this error message:
```
org.postgresql.util.PSQLException: Connection to instrumentationdb-primary.ibm-common-services.svc:5432 refused.
 Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```
I found the instrumentationdb PostgresCluster the status is as follows:

```
status:
  conditions:
    - lastTransitionTime: '2023-07-17T05:04:09Z'
      message: pgBackRest dedicated repository host is ready
      observedGeneration: 7
      reason: RepoHostReady
      status: 'True'
      type: PGBackRestRepoHostReady
    - lastTransitionTime: '2023-07-17T05:04:02Z'
      message: pgBackRest replica create repo is not ready for backups
      observedGeneration: 7
      reason: StanzaNotCreated
      status: 'False'
      type: PGBackRestReplicaRepoReady
    - lastTransitionTime: '2023-07-17T05:04:02Z'
      message: pgBackRest replica creation is not currently possible
      observedGeneration: 7
      reason: RepoBackupNotComplete
      status: 'False'
      type: PGBackRestReplicaCreate
```

Am I missing something, or is there something else I can check to see why this service is not running?

Appreciate your help.

Thank you.
