### ISSUE TITLE
mas install pre check fails on ARO cluster

### ISSUE THREAD

**Issue by kathleenhosang** [ibm-mas/installer#561]
Running `mas install` on ARO cluster yields the following error message:

```
TASK [ibm.mas_devops.ocp_verify : Debug cluster certificate secret search] *****
ok: [localhost] => 
  msg:
  - Found Router Default Secret ........... False
  - Found Cluster Ingress Secret .......... False
  - Found Cluster Primary Secret .......... False
  - Cluster Ingress Cert Secret Name ...... missing
  - Cluster Ingress Cert .................. missing

TASK [ibm.mas_devops.ocp_verify : Fail if one of the cluster required secrets does not exist] ***
fatal: [localhost]: FAILED! => changed=false 
  assertion: cluster_ingress_secret_name is defined
  evaluated_to: false
  msg: This cluster does not contain any of the secrets known to contain the TLS certificate for the cluster ingress.

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=1    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   

```
Saw issue in client environment and replicated issue in test ARO cluster.

I looked at the default ingress controller configuration in test env and can see the default ingress certificate as part of the yaml file:

```
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  creationTimestamp: "2023-10-16T19:59:03Z"
  finalizers:
  - ingresscontroller.operator.openshift.io/finalizer-ingresscontroller
  generation: 2
  name: default
  namespace: openshift-ingress-operator
  resourceVersion: "46153"
  uid: 6df12313-5db2-47a8-993f-06899e95ca60
spec:
  clientTLS:
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  defaultCertificate:
    name: e89b2efb-e26c-447a-89d3-29a9160ba725-ingress
```

I should be able to get around this by using the ansible playbooks directly, but wanted to raise, since it will be difficult to manage ARO clusters without mas cli support.

**Comment by durera** [comment]
Been meaning to make improvements in this area for a while, using this as the kick to finally do it...

**Comment by durera** [comment]
I have no access to a system to test the fix .. @kathleenhosang could you try please see if this change helps: 

Start a docker container with the fix: `docker run -ri quay.io/ibmmas/cli:7.4.4-pre.ingress`

Inside the container, create a playbook like so `ocpverify.yaml`:

```yaml
- hosts: localhost
  any_errors_fatal: true
  vars:
    verify_cluster: False
    verify_catalogsources: False
    verify_subscriptions: False
    verify_workloads: False
    verify_ingres: True
  roles:
    - ibm.mas_devops.ocp_verify
```

Run the playbook: `ansible-playbook ocpverify.yaml`

Should hopefully see output like this:

```
TASK [ocp_verify : Debug cluster certificate secret search] ********
ok: [localhost] =>
  msg:
  - Found Router Default Secret ........... False
  - Found Cluster Ingress Secret .......... False
  - Found Cluster Primary Secret .......... False
  - Found Ingress Controller Secret ....... True
  - Cluster Ingress Cert Secret Name ...... YOURCERTNAME

TASK [ocp_verify : Fail if one of the cluster required secrets does not exist] *******
ok: [localhost] => changed=false
  msg: All assertions passed
```

I don't have any clusters where the first 3 ways of finding the certificate fails, I had hoped the IngressController would be a universal way to get the secret name, but sadly it's as fallable as the others; there doesn't seem to be a single reliable way to look this up that works across all OCP clusters.
