### ISSUE TITLE
Prometheus monitoring may fail if installing with defaults

### ISSUE THREAD

**Issue by rene-oromtz** [ibm-mas/installer#840]
Summary
----
During mas install, if going with defaults, the default retention period may not be suitable for all customers. 
Whenever prometheus PVC gets full, it won't be able to handle this and monitoring will start to crash, no dashboards will be available and manual intervention is needed

```
$ oc get co|grep monitoring
monitoring                 4.12.37  False    True     True    89m   NoPodReady: shard 0: pod prometheus-k8s-0: containers with unready status: [prometheus]...
```

Steps to reproduce
----
1. Install Maximo with defaults
2. Continue with regular usage
3. After few days (depending on workload), PVC will start to get full, if no intervention to cleanup or reduce the default retention period, PVC will be full and dashboard will start to crash

Possible fixes
----
Modify retention period to decrease the default retention time. Default storage is only 20Gb so 15 days of days is a lot for the PVC to handle. I know that increasing the PVC size might not be suitable for all cluster so retention days might be the way to go. 

Current defaults for openshift-monitoring:
```
# Settings to update openshift monitoring to define a specific storage class for Prometheus logs
prometheus_retention_period: "{{ lookup('env', 'PROMETHEUS_RETENTION_PERIOD') | default('15d', true) }}"
prometheus_storage_class: "{{ lookup('env', 'PROMETHEUS_STORAGE_CLASS') }}"
prometheus_storage_size: "{{ lookup('env', 'PROMETHEUS_STORAGE_SIZE') | default('20Gi', true) }}"
prometheus_alertmgr_storage_class: "{{ lookup('env', 'PROMETHEUS_ALERTMGR_STORAGE_CLASS') }}"
prometheus_alertmgr_storage_size: "{{ lookup('env', 'PROMETHEUS_ALERTMGR_STORAGE_SIZE') | default('20Gi', true) }}"
```

Workaround
----
1.Manually modify retention days from ConfigMap cluster-monitoring-config in openShift-monitoring namespace AFTER installing Maximo (storage size can also be increased to handle this situation)

```
apiVersion: v1
data:
  config.yaml: |
    prometheusOperator:
      baseImage: quay.io/coreos/prometheus-operator
      prometheusConfigReloaderBaseImage: quay.io/coreos/prometheus-config-reloader
      configReloaderBaseImage: quay.io/coreos/configmap-reload
    prometheusK8s:
      retention: "3d"
      baseImage: openshift/prometheus
      volumeClaimTemplate:
        spec:
          storageClassName: "ibm-storage-fusion-cp-sc"
          resources:
            requests:
              storage: "20Gi"
    alertmanagerMain:
      baseImage: openshift/prometheus-alertmanager
      volumeClaimTemplate:
        spec:
          storageClassName: "ibm-storage-fusion-cp-sc"
          resources:
            requests:
              storage: "20Gi"
```

2. Modify defaults while installing MAS:
```
Change Cluster monitoring storage defaults? [y/N] y
+ Grafana Storage Size > 10Gi
+ Prometheus Retention Period > 15d
+ Prometheus Storage Size > 300Gi
+ Prometheus Alert Mgr Storage Size > 300Gi
+ Prometheus User Workload Retention Period > 15d
+ Prometheus User Workload Storage Size > 300Gi
```

3. If prometheus is already down, there are two options. Either increase PVC size and restart prometheus-k8s pods or remove */wal content, this causes data loss
From any node:
```
$ cd /var/lib/kubelet/pods/da53f356-7f4c-4f90-a74d-72dbd6c02936/volumes/kubernetes.io~csi/pvc-715c1ba7-774c-4ab9-8397-810b9292c82d/mount/prometheus-db
$ rm -r wal/*
```

```
$ oc get pvc -n openshift-monitoring|grep prometheus
prometheus-k8s-db-prometheus-k8s-0         Bound    pvc-715c1ba7-774c-4ab9-8397-810b9292c82d   100Gi      RWO            ibm-storage-fusion-cp-sc   16d
prometheus-k8s-db-prometheus-k8s-1         Bound    pvc-6b94dab9-12b9-4f61-8ff7-28888b514ff7   100Gi      RWO            ibm-storage-fusion-cp-sc   16d
```

```
$ oc get pod -n openshift-monitoring|grep prometheus-k8s
prometheus-k8s-0                                        6/6     Running   6 (94m ago)   97m
prometheus-k8s-1                                        6/6     Running   0             97m
```
