### ISSUE TITLE
[ROSA] MAS deployment via Tekton Pipeline - service account lacks permissions

### ISSUE THREAD

**Issue by Daniel-M-Jacobson** [ibm-mas/installer#923]
In both ROSA and ROSA HCP, there are webhooks that disallow creating objects in certain namespaces. 
"Prevented from accessing Red Hat managed namespaces."

[UDS_403Forbidden.txt](https://github.com/ibm-mas/cli/files/15149761/UDS_403Forbidden.txt)

After some discussion with a red hat architect, I was pointed to this code
https://github.com/openshift/managed-cluster-validating-webhooks/blob/master/pkg/webhooks/namespace/namespace.go#L220

When deploying MAS on pipeline, the service account does not have sufficient permissions to install MAS because of namespace choices. 

I was able to successfully complete the same task by running installation from the ansible playbook as cluster-admin.

**Comment by durera** [comment]
The CLI sets up the pipelines to run under a serviceaccount with admin permissions ... in the logs provided it's complaining that the catalogsources can't be created in `openshift-marketplace`, did the red hat architect provide any information on how to allow a service account to work in these "managed namespaces", it sounds like you could do so just fine as a cluster-admin, but that's the same permission the service account we're running the pipelines under should have. 

I don't specifically have access to ROSA or ROSA HCP to test I'm afraid, but I'd expect the pipelines service account to have the permissions you had when you ran as cluster-admin due to this ClusterRoleBinding:

```yaml
# 1. Configure RBAC for the pipeline tasks
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-mas-pipeline-{{mas_instance_id}}
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: mas-{{mas_instance_id}}-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```
