### ISSUE TITLE
`mas update` fails in the `update-mongodb` task for SNO 

### ISSUE THREAD

**Issue by mudspringhiker** [ibm-mas/installer#924]
When running `mas update` for MAS in SNO, it fails in the `update-mongodb` task, waiting for mas-mongo-ce stateful set to be ready. MongoDBCommunity CR status is "Pending".

```
status:
  currentMongoDBMembers: 1
  currentStatefulSetReplicas: 1
  message: ReplicaSet is not yet ready, retrying in 10 seconds
  mongoUri: mongodb://mas-mongo-ce-0.mas-mongo-ce-svc.mongoce.svc.cluster.local:27017/?replicaSet=mas-mongo-ce
  phase: Pending
  version: 5.0.23
```

It appears that MongoDBCommunity CR spec.members is 3. Comparing this to a different, newly installed MAS on SNO, its MongoDBCommunity CR spec.members is 1. Changing the spec.members in the instance being updated above to 1 fixed the issue.
